services:
  gateway-service:
    build:
      context: ./gateway-service
      dockerfile: Dockerfile
    container_name: gateway-service
    ports:
      - 8080:8080
  common-service:
    build:
      context: ./common-service/common-biz
      dockerfile: Dockerfile
    container_name: common-service
    ports:
      - 8081:8081
  admin-service:
    build:
      context: ./admin-service
      dockerfile: Dockerfile
    container_name: admin-service
    ports:
      - 8082:8082
    depends_on:
      - common-service
  client-service:
    build:
      context: ./client-service
      dockerfile: Dockerfile
    container_name: client-service
    ports:
      - 8083:8083
    depends_on:
      - common-service

# 创建相关镜像、容器、网络、卷并启动容器
# docker compose -f ./docker-compose.yaml -p cloud-bookstore up -d
# 停止并移除相关容器、网络、卷和通过 docker compose 构建的本地镜像
# docker compose -f ./docker-compose.yaml -p cloud-bookstore down --rmi local